# Native remote deploy (Windows OpenSSH -> Ubuntu binary + systemd, no Docker).
# Usage: powershell -File scripts/remote-native.ps1 <action>
# Actions: check|env|fetch|sync|install|up|down|restart|logs|status|deploy

param(
  [Parameter(Position = 0, Mandatory = $true)]
  [ValidateSet('check', 'env', 'fetch', 'sync', 'install', 'up', 'down', 'restart', 'logs', 'status', 'deploy')]
  [string]$Action
)

$ErrorActionPreference = 'Stop'
$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
Set-Location $Root

function Read-DotEnv {
  param([string]$Path)
  $map = @{}
  if (-not (Test-Path $Path)) { return $map }
  Get-Content $Path | ForEach-Object {
    $line = $_.Trim()
    if (-not $line -or $line.StartsWith('#')) { return }
    $eq = $line.IndexOf('=')
    if ($eq -lt 1) { return }
    $k = $line.Substring(0, $eq).Trim()
    $v = $line.Substring($eq + 1).Trim()
    # strip inline comments for simple KEY=value  # comment lines
    if ($v -match '^([^#]*?)(\s+#.*)$') { $v = $Matches[1].Trim() }
    if (($v.StartsWith('"') -and $v.EndsWith('"')) -or ($v.StartsWith("'") -and $v.EndsWith("'"))) {
      $v = $v.Substring(1, $v.Length - 2)
    }
    $map[$k] = $v
  }
  return $map
}

function Resolve-OpenSsh {
  param([Parameter(Mandatory = $true)][ValidateSet('ssh', 'scp')][string]$Name)
  $file = "$Name.exe"
  $candidates = @(
    (Join-Path $env:SystemRoot "Sysnative\OpenSSH\$file"),
    (Join-Path $env:SystemRoot "System32\OpenSSH\$file")
  )
  try {
    $whereHits = & where.exe $file 2>$null
    if ($whereHits) { foreach ($hit in @($whereHits)) { if ($hit -and (Test-Path -LiteralPath $hit)) { $candidates += $hit } } }
  } catch {}
  $gitSsh = Join-Path ${env:ProgramFiles} "Git\usr\bin\$file"
  if (Test-Path -LiteralPath $gitSsh) { $candidates += $gitSsh }
  foreach ($c in $candidates) {
    if ($c -and (Test-Path -LiteralPath $c)) { return (Resolve-Path -LiteralPath $c).Path }
  }
  throw "Missing $file - install OpenSSH Client"
}

$SshExe = Resolve-OpenSsh ssh
$ScpExe = Resolve-OpenSsh scp
$envMap = Read-DotEnv (Join-Path $Root '.env')
$hostName = $envMap['DEPLOY_HOST']
$user = if ($envMap['DEPLOY_USER']) { $envMap['DEPLOY_USER'] } else { 'ubuntu' }
$deployPath = if ($envMap['DEPLOY_PATH']) { $envMap['DEPLOY_PATH'] } else { '/opt/gantry' }
$sshPort = if ($envMap['DEPLOY_SSH_PORT']) { $envMap['DEPLOY_SSH_PORT'] } else { '22' }
$key = $envMap['DEPLOY_SSH_KEY']
$gantryVersion = if ($envMap['GANTRY_VERSION']) { $envMap['GANTRY_VERSION'] } else { 'latest' }
$dockerHost = $envMap['NATIVE_DOCKER_HOST']
$dockerContainer = if ($envMap['NATIVE_DOCKER_CONTAINER']) { $envMap['NATIVE_DOCKER_CONTAINER'] } else { 'gantry' }
$llmModel = if ($envMap['NATIVE_LLM_MODEL']) { $envMap['NATIVE_LLM_MODEL'] } else { 'qwen3.5:35b' }

if (-not $hostName -and $Action -ne 'env' -and $Action -ne 'fetch') {
  throw "Set DEPLOY_HOST in .env"
}

$sshArgs = @('-p', $sshPort, '-o', 'StrictHostKeyChecking=accept-new')
$scpArgs = @('-P', $sshPort, '-o', 'StrictHostKeyChecking=accept-new')
if ($key) {
  if (-not (Test-Path -LiteralPath $key)) { throw "DEPLOY_SSH_KEY not found: $key" }
  $sshArgs += @('-i', $key)
  $scpArgs += @('-i', $key)
}
$target = "${user}@${hostName}"
$Cache = Join-Path $Root '.cache\native'
$StageRemote = '/tmp/gantry-native'
$DeployDir = Join-Path $Root 'deploy'

function Invoke-Remote([string]$RemoteCmd) {
  & $SshExe @sshArgs $target $RemoteCmd
  if ($LASTEXITCODE -ne 0) { throw "Remote command failed ($LASTEXITCODE): $RemoteCmd" }
}

function Invoke-RemoteTTY([string]$RemoteCmd) {
  & $SshExe @sshArgs -t $target $RemoteCmd
  if ($LASTEXITCODE -ne 0) { throw "Remote command failed ($LASTEXITCODE): $RemoteCmd" }
}

function Get-ReleaseTag {
  if ($gantryVersion -ne 'latest') { return $gantryVersion }
  $api = Invoke-RestMethod -Uri 'https://api.github.com/repos/shotah/ai-gantry/releases/latest' -Headers @{ 'User-Agent' = 'ai-gantry-remote-native' }
  return $api.tag_name
}

function Write-NativeEnv {
  $src = Read-DotEnv (Join-Path $Root '.env')
  if (-not $src['TELEGRAM_BOT_TOKEN']) { throw ".env missing TELEGRAM_BOT_TOKEN" }
  if (-not $src['TELEGRAM_ALLOWED_USERS']) { throw ".env missing TELEGRAM_ALLOWED_USERS" }

  $out = Join-Path $DeployDir 'gantry.env'
  $tz = if ($src['TZ']) { $src['TZ'] } else { 'America/Los_Angeles' }
  $stream = if ($src['STREAM_REPLIES']) { $src['STREAM_REPLIES'] } else { 'true' }
  $lines = @(
    '# Generated by make remote-native-env - do not commit',
    'HOME=/opt/gantry/data',
    'DATA_DIR=/opt/gantry/data',
    'PERSONA_DIR=/opt/gantry/persona',
    'MCP_MANIFEST=/opt/gantry/mcp.toml',
    'LLM_BASE_URL=http://127.0.0.1:11434/v1',
    'LLM_API_KEY=ollama',
    "LLM_MODEL=$llmModel",
    # Qwen3.5 thinking eats the completion budget unless reasoning_effort=none.
    "LLM_MAX_TOKENS=$(if ($src['LLM_MAX_TOKENS']) { $src['LLM_MAX_TOKENS'] } else { '16384' })",
    "LLM_REASONING_EFFORT=$(if ($src['LLM_REASONING_EFFORT']) { $src['LLM_REASONING_EFFORT'] } else { 'none' })",
    'CHANNEL=telegram',
    "TELEGRAM_BOT_TOKEN=$($src['TELEGRAM_BOT_TOKEN'])",
    "TELEGRAM_ALLOWED_USERS=$($src['TELEGRAM_ALLOWED_USERS'])",
    "STREAM_REPLIES=$stream",
    'LOG_LEVEL=info',
    "TZ=$tz",
    "CRON_TZ=$tz",
    'CRON_ENABLED=true',
    "GEMINI_API_KEY=$($src['GEMINI_API_KEY'])",
    "GEMINI_MODEL=$(if ($src['GEMINI_MODEL']) { $src['GEMINI_MODEL'] } else { 'gemini-3.5-flash' })",
    "GOOGLE_OAUTH_CLIENT_ID=$($src['GOOGLE_OAUTH_CLIENT_ID'])",
    "GOOGLE_OAUTH_CLIENT_SECRET=$($src['GOOGLE_OAUTH_CLIENT_SECRET'])",
    "USER_GOOGLE_EMAIL=$($src['USER_GOOGLE_EMAIL'])",
    'WORKSPACE_MCP_CREDENTIALS_DIR=/opt/gantry/data/.config/google-mcp/credentials',
    "STRAVA_CLIENT_ID=$($src['STRAVA_CLIENT_ID'])",
    "STRAVA_CLIENT_SECRET=$($src['STRAVA_CLIENT_SECRET'])",
    'STRAVA_TOKEN_PATH=/opt/gantry/data/.config/strava/tokens.json',
    'YTMUSIC_HEADERS_PATH=/opt/gantry/data/.config/ytmusic/headers.json'
  )
  New-Item -ItemType Directory -Force -Path $DeployDir | Out-Null
  Set-Content -LiteralPath $out -Value $lines -Encoding utf8
  Write-Host "Wrote $out (Ollama model=$llmModel)"
}

function Fetch-GantryBinary {
  New-Item -ItemType Directory -Force -Path $Cache | Out-Null
  $tag = Get-ReleaseTag
  $ver = $tag.TrimStart('v')
  $asset = "gantry_${ver}_linux_amd64.tar.gz"
  $url = "https://github.com/shotah/ai-gantry/releases/download/$tag/$asset"
  $tarball = Join-Path $Cache $asset
  Write-Host "Fetching $url"
  Invoke-WebRequest -Uri $url -OutFile $tarball -UseBasicParsing
  $extract = Join-Path $Cache 'extract'
  if (Test-Path $extract) { Remove-Item -Recurse -Force $extract }
  New-Item -ItemType Directory -Force -Path $extract | Out-Null
  tar -xzf $tarball -C $extract
  $bin = Join-Path $extract 'gantry'
  if (-not (Test-Path $bin)) { throw "tarball missing gantry binary" }
  Copy-Item $bin (Join-Path $Cache 'gantry') -Force
  Write-Host "Cached gantry $tag -> .cache/native/gantry"
}

function Fetch-ToolsFromDocker {
  if (-not $dockerHost) {
    Write-Host "NATIVE_DOCKER_HOST unset - skipping MCP tool extract (kernel-only ok)"
    return
  }
  $binDir = Join-Path $Cache 'bin'
  New-Item -ItemType Directory -Force -Path $binDir | Out-Null
  $tools = @(
    'gantry',
    'google-workspace-mcp-go',
    'strava-mcp',
    'garmin',
    'mcp-gemini-google-search',
    'mcp-beam',
    'youtube-go-mcp'
  )
  $remoteTmp = '/tmp/gantry-docker-bin'
  $dockerUser = if ($envMap['NATIVE_DOCKER_USER']) { $envMap['NATIVE_DOCKER_USER'] } else { $user }
  # Prefer same SSH key as DEPLOY_*; only the host changes.
  Write-Host "Extracting tools from docker:$dockerContainer on $dockerHost"
  $extractSh = @"
set -e
rm -rf $remoteTmp
mkdir -p $remoteTmp
for b in $($tools -join ' '); do
  docker cp ${dockerContainer}:/usr/local/bin/`$b $remoteTmp/`$b
done
chmod a+x $remoteTmp/*
ls -la $remoteTmp
"@
  $extractLocal = Join-Path $Cache 'extract-tools.sh'
  # UTF-8 no BOM - bash on Linux rejects BOM as a bad interpreter line
  [System.IO.File]::WriteAllText($extractLocal, ($extractSh -replace "`r`n", "`n"))
  & $ScpExe @scpArgs $extractLocal "${dockerUser}@${dockerHost}:/tmp/extract-gantry-tools.sh"
  if ($LASTEXITCODE -ne 0) { throw "scp extract script to docker host failed" }
  & $SshExe @sshArgs "${dockerUser}@${dockerHost}" "bash /tmp/extract-gantry-tools.sh"
  if ($LASTEXITCODE -ne 0) { throw "docker cp tool extract failed on $dockerHost" }
  & $ScpExe @scpArgs -r "${dockerUser}@${dockerHost}:${remoteTmp}/." "$binDir/"
  if ($LASTEXITCODE -ne 0) { throw "scp tools from docker host failed" }
  # Prefer release gantry if present; docker copy overwrites - keep docker gantry as fine too.
  if (Test-Path (Join-Path $binDir 'gantry')) {
    Copy-Item (Join-Path $binDir 'gantry') (Join-Path $Cache 'gantry') -Force
  }
  Write-Host "Tools cached under .cache/native/bin"
}

function Sync-Stage {
  $gantryBin = Join-Path $Cache 'gantry'
  if (-not (Test-Path $gantryBin)) { throw "Missing .cache/native/gantry - run fetch first" }
  $envFile = Join-Path $DeployDir 'gantry.env'
  if (-not (Test-Path $envFile)) { throw "Missing deploy/gantry.env - run make remote-native-env" }

  Write-Host "Staging -> ${target}:${StageRemote}"
  Invoke-Remote "rm -rf $StageRemote && mkdir -p $StageRemote/bin $StageRemote/persona"
  & $ScpExe @scpArgs $gantryBin "${target}:${StageRemote}/gantry"
  if ($LASTEXITCODE -ne 0) { throw 'scp gantry failed' }
  & $ScpExe @scpArgs (Join-Path $DeployDir 'gantry.service') "${target}:${StageRemote}/gantry.service"
  & $ScpExe @scpArgs (Join-Path $DeployDir 'install.sh') "${target}:${StageRemote}/install.sh"
  & $ScpExe @scpArgs $envFile "${target}:${StageRemote}/gantry.env"
  $mcp = Join-Path $Root 'mcp.toml'
  if (Test-Path $mcp) { & $ScpExe @scpArgs $mcp "${target}:${StageRemote}/mcp.toml" }

  $binDir = Join-Path $Cache 'bin'
  if (Test-Path $binDir) {
    Get-ChildItem $binDir -File | ForEach-Object {
      & $ScpExe @scpArgs $_.FullName "${target}:${StageRemote}/bin/$($_.Name)"
      if ($LASTEXITCODE -ne 0) { throw "scp tool $($_.Name) failed" }
    }
  }

  # Persona: prefer live local-agent/persona, else skip (already on host).
  $persona = Join-Path $Root 'persona'
  $personaFiles = @()
  if (Test-Path $persona) {
    $personaFiles = @(Get-ChildItem $persona -Filter '*.md' -File | Where-Object { $_.Name -notlike '*.example.md' })
  }
  if ($personaFiles.Count -gt 0) {
    foreach ($f in $personaFiles) {
      & $ScpExe @scpArgs $f.FullName "${target}:${StageRemote}/persona/$($f.Name)"
    }
  } else {
    Write-Host "No local persona/*.md - leaving host persona untouched at install"
  }

  Invoke-Remote "chmod +x $StageRemote/gantry $StageRemote/install.sh $StageRemote/bin/* 2>/dev/null; ls -la $StageRemote; ls -la $StageRemote/bin 2>/dev/null || true"
  Write-Host "Staged. Install with: make remote-native-install"
}

function Install-Remote {
  Write-Host "Installing via sudo (password prompt if needed)..."
  Invoke-RemoteTTY "sudo bash $StageRemote/install.sh"
}

switch ($Action) {
  'check' {
    Write-Host "Checking native host ${target} ($deployPath)"
    Invoke-Remote "echo ok && uname -a && systemctl is-active ollama && test -d $deployPath && id gantry && ollama ps && echo NATIVE_OK"
  }
  'env' { Write-NativeEnv }
  'fetch' {
    Fetch-GantryBinary
    Fetch-ToolsFromDocker
  }
  'sync' { Sync-Stage }
  'install' { Install-Remote }
  'up' { Invoke-RemoteTTY "sudo systemctl start gantry && systemctl --no-pager --full status gantry | head -n 20" }
  'down' { Invoke-RemoteTTY "sudo systemctl stop gantry && echo stopped" }
  'restart' { Invoke-RemoteTTY "sudo systemctl restart gantry && systemctl --no-pager --full status gantry | head -n 20" }
  'logs' { Invoke-RemoteTTY "journalctl -u gantry -f -n 100" }
  'status' { Invoke-RemoteTTY "systemctl is-active gantry; sudo -u gantry $deployPath/gantry status; echo OK" }
  'deploy' {
    Write-NativeEnv
    Fetch-GantryBinary
    Fetch-ToolsFromDocker
    Sync-Stage
    Install-Remote
    Invoke-RemoteTTY "sudo systemctl restart gantry && systemctl --no-pager --full status gantry | head -n 25"
    Write-Host "Deployed. Message TIM on Telegram; logs: make remote-native-logs"
  }
}
